version: 2

models:
  - name: dbt_test__films
    description: "This table contains details about films."
    columns:
      - name: film_id
        description: "Unique identifier for the film."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released."
        tests:
          - not_null
      - name: price
        description: "Price to buy a ticket."
        tests:
          - not_null
          - is_price_positive
      - name: rating
        description: "The MPAA rating of the film."
        tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the film."
        tests:
          - not_null
    
  - name: dbt_test__actors
    description: "This table contains details about actors."
    columns:
      - name: actor_id
        description: "Unique identifier for the actor."
        tests:
          - unique
          - not_null
      - name: name
        description: "First name of the actor."

  - name: dbt_test__film_actors
    description: "This table maps films to the actors that starred in them."
    columns:
      - name: film_id
        description: "Identifier for the film."
        tests:
          - not_null
      - name: actor_id
        description: "Identifier for the actor."
        tests:
          - not_null

  - name: film_ratings
    description: "This model aggregates film data and calculates the average rating for each film."
    columns:
      - name: film_id
        description: "The unique identifier for each film."
        tests:
          - unique
          - not_null

      - name: title
        description: "The title of the film."
        tests:
          - not_null

      - name: release_date
        description: "The release date of the film."
        tests:
          - not_null

      - name: price
        description: "The price of the film."
        tests:
          - not_null

      - name: rating
        description: "The MPAA rating of the film."

      - name: user_rating
        description: "The average user rating for the film."
        tests:
          - not_null
    
  - name: count_rating
    description: "Count of rating category"
    columns:
      - name: rating
        description: "The number of rating category."
        tests:
          - not_null

      - name: total_rating
        description: "total count per rating"

  
  - name: film_under_10_price
    description: "Film with price under 10 dolar"
    columns:
      - name: film_id
        description: "Unique identifier for the film."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released."
        tests:
          - not_null
      - name: price
        description: "Price to buy a ticket."
        tests:
          - not_null
          - is_price_positive
      - name: rating
        description: "The MPAA rating of the film."
        tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the film."
        tests:
          - not_null
  
  - name: film_category
    description: "Film with category user rating"
    columns:
      - name: film_id
        description: "id film"
        tests:
          - not_null
          - unique
      - name: title
        description: "title film"
      - name: release_date
        description: "release date of film"
      - name: user_rating_category
        description: "category user rating"